default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.4.1
    hooks:
      - id: pyupgrade
        args: [--py38-plus]

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args: [--config, ./pyproject.toml]
