# SPDX-FileCopyrightText: 2020 Pynguin Contributors
#
# SPDX-License-Identifier: LGPL-3.0-or-later

version: 2
sphinx:
  configuration: docs/conf.py

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
