[tool.poetry]
name = "pynguin"
version = "0.1.0"
description = "An automated Python random unit test generation tool inspired by Randoop"
authors = ["Stephan Lukasczyk <stephan@lukasczyk.me>"]
license = "LGPL-3.0+"
readme = "README.md"
repository = "https://github.com/stephanlukasczyk/pynguin"
keywords = "unit test, generation, randoop, automated"
classifiers = [
    "Development Status :: 1 - Planning",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Topic :: Education :: Testing",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Testing :: Unit",
]

[tool.poetry.dependencies]
python = "^3.7"
coverage = "^4.5"
configargparse = "^0.14"
astor = "^0.8.0"

[tool.poetry.dev-dependencies]
pytest = "^5.0"
black = {version = "^19.3b0", allows-prereleases = true}
flake8 = "^3.7"
pytest-cov = "^2.7"
mypy = "^0.720"
pylint = "^2.3"

[tool.poetry.scripts]
pynguin = "pynguin.cli:main"

[tool.black]
line-length = 88
target_version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs          # exclude a few common directories in the
    | \.git           # root of the project
    | \.pytest_cache
    | \.mypy_cache
    | \.venv
    | _build
    | build
    | dist
    | pynguin.egg-info
  )/
)
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
